services:
  - type: web
    name: helphub-backend
    runtime: node
    plan: free
    rootDir: backend_node
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20

  - type: web
    env: static
    name: helphub-frontend
    rootDir: frontend_react
    staticPublishPath: ./dist
    buildCommand: npm install --include=dev && npm run build
    envVars:
      - key: NODE_VERSION
        value: 20
